---
title: "DSC640_5.2_Assignment"
author: "Sathish Manthani"
date: "8/7/2020"
output: word_document
---



```{r data_import}
birth <- read.csv('birth-rate.csv')

crime <- read.csv('crimeratesbystate-formatted.csv') 

education <- read.csv('education.csv') 


```


```{r histogram}
options(repr.plot.width = 4, repr.plot.height = 4)

birth1 <- reshape2::melt(birth, id=c("Country")) %>%
  dplyr::mutate("Country" = as.character(Country),
                "Year" = as.character(variable),
                "Population" = value) %>% 
  dplyr::select(c("Country","Year","Population"))

hist(birth1$Population, col=rgb(0.4,0.9,0.2,0.5) , border=F , main="Population Histogram", xlab = "Population", ylab = 'Frequency')

```

```{r boxplot}

birth2 <- birth1 %>% 
  dplyr::filter(Country %in% c("United States", "India","China", "Canada"))

boxplot(birth2$Population ~ birth2$Country , col="grey", xlab="Country", ylab="Population")

```


```{r bullet}
library(plotly)

fig <- plot_ly(
  type = "indicator",
  mode = "number+gauge+delta",
  value = 220,
  domain = list(x = c(0, 1), y= c(0, 1)),
  title = list(text = "<b>Profit</b>"),
  delta = list(reference = 200),
  gauge = list(
    shape = "bullet",
    axis = list(range = list(NULL, 300)),
    threshold = list(
      line = list(color = "red", width = 2),
      thickness = 0.75,
      value = 250),
    steps = list(
      list(range = c(0, 150), color = "lightgray"),
      list(range = c(150, 240), color = "gray"))),
  height = 150, width = 600) 
fig <- fig %>%
  layout(margin = list(l= 100, r= 10))

fig
```
